// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_plane.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminSessionView = `-- name: AdminSessionView :many
SELECT
    admin.admin_user_id,
    admin.email,
    admin.display_name,
    admin.status,
    membership.organization_id,
    membership.role
FROM admin_users AS admin
JOIN admin_memberships AS membership
    ON membership.admin_user_id = admin.admin_user_id
WHERE admin.admin_user_id = $1
  AND admin.status = 'active'
  AND membership.status = 'active'
ORDER BY membership.organization_id
`

type AdminSessionViewRow struct {
	AdminUserID    string `db:"admin_user_id" json:"admin_user_id"`
	Email          string `db:"email" json:"email"`
	DisplayName    string `db:"display_name" json:"display_name"`
	Status         string `db:"status" json:"status"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
	Role           string `db:"role" json:"role"`
}

func (q *Queries) AdminSessionView(ctx context.Context, adminUserID string) ([]AdminSessionViewRow, error) {
	rows, err := q.db.Query(ctx, adminSessionView, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSessionViewRow{}
	for rows.Next() {
		var i AdminSessionViewRow
		if err := rows.Scan(
			&i.AdminUserID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.OrganizationID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    application_id,
    organization_id,
    slug,
    display_name,
    status,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, 'active', $5, $5)
RETURNING application_id, organization_id, slug, display_name, status, disabled_at, created_at, updated_at
`

type CreateApplicationParams struct {
	ApplicationID  string             `db:"application_id" json:"application_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CreateApplicationRow struct {
	ApplicationID  string             `db:"application_id" json:"application_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (CreateApplicationRow, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ApplicationID,
		arg.OrganizationID,
		arg.Slug,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i CreateApplicationRow
	err := row.Scan(
		&i.ApplicationID,
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    environment_id,
    organization_id,
    application_id,
    slug,
    display_name,
    kind,
    status,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, 'active', $7, $7)
RETURNING environment_id, organization_id, application_id, slug, display_name, kind, status, disabled_at, created_at, updated_at
`

type CreateEnvironmentParams struct {
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Kind           string             `db:"kind" json:"kind"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CreateEnvironmentRow struct {
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Kind           string             `db:"kind" json:"kind"`
	Status         string             `db:"status" json:"status"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (CreateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.EnvironmentID,
		arg.OrganizationID,
		arg.ApplicationID,
		arg.Slug,
		arg.DisplayName,
		arg.Kind,
		arg.CreatedAt,
	)
	var i CreateEnvironmentRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OrganizationID,
		&i.ApplicationID,
		&i.Slug,
		&i.DisplayName,
		&i.Kind,
		&i.Status,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    organization_id,
    slug,
    display_name,
    status,
    created_at,
    updated_at
) VALUES ($1, $2, $3, 'active', $4, $4)
RETURNING organization_id, slug, display_name, status, created_at, updated_at
`

type CreateOrganizationRow struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, organizationID string, slug string, displayName string, createdAt pgtype.Timestamptz) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		organizationID,
		slug,
		displayName,
		createdAt,
	)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT application_id, organization_id, slug, display_name, status, disabled_at, created_at, updated_at
FROM applications
WHERE organization_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, application_id) > (
          $2::timestamptz,
          $3::text
      )
  )
ORDER BY created_at, application_id
LIMIT $4
`

type ListApplicationsRow struct {
	ApplicationID  string             `db:"application_id" json:"application_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListApplications(ctx context.Context, organizationID string, cursorCreatedAt pgtype.Timestamptz, cursorID *string, pageLimit int32) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications,
		organizationID,
		cursorCreatedAt,
		cursorID,
		pageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsRow{}
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.OrganizationID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT environment_id, organization_id, application_id, slug, display_name, kind, status, disabled_at, created_at, updated_at
FROM environments
WHERE organization_id = $1
  AND application_id = $2
ORDER BY created_at, environment_id
`

type ListEnvironmentsRow struct {
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Kind           string             `db:"kind" json:"kind"`
	Status         string             `db:"status" json:"status"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListEnvironments(ctx context.Context, organizationID string, applicationID string) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, organizationID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.OrganizationID,
			&i.ApplicationID,
			&i.Slug,
			&i.DisplayName,
			&i.Kind,
			&i.Status,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForAdmin = `-- name: ListOrganizationsForAdmin :many
SELECT
    organization.organization_id,
    organization.slug,
    organization.display_name,
    organization.status,
    membership.role,
    organization.created_at,
    organization.updated_at
FROM organizations AS organization
JOIN admin_memberships AS membership
    ON membership.organization_id = organization.organization_id
WHERE membership.admin_user_id = $1
  AND membership.status = 'active'
  AND organization.status = 'active'
  AND (
      $2::timestamptz IS NULL
      OR (organization.created_at, organization.organization_id) > (
          $2::timestamptz,
          $3::text
      )
  )
ORDER BY organization.created_at, organization.organization_id
LIMIT $4
`

type ListOrganizationsForAdminRow struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	Role           string             `db:"role" json:"role"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListOrganizationsForAdmin(ctx context.Context, adminUserID string, cursorCreatedAt pgtype.Timestamptz, cursorID *string, pageLimit int32) ([]ListOrganizationsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForAdmin,
		adminUserID,
		cursorCreatedAt,
		cursorID,
		pageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForAdminRow{}
	for rows.Next() {
		var i ListOrganizationsForAdminRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
