// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveConfigRevision struct {
	OrganizationID         string             `db:"organization_id" json:"organization_id"`
	ApplicationID          string             `db:"application_id" json:"application_id"`
	EnvironmentID          string             `db:"environment_id" json:"environment_id"`
	ConfigRevisionID       string             `db:"config_revision_id" json:"config_revision_id"`
	RevisionStatus         string             `db:"revision_status" json:"revision_status"`
	ActivatedByAdminUserID string             `db:"activated_by_admin_user_id" json:"activated_by_admin_user_id"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
}

type AdminApiToken struct {
	AdminApiTokenID      string             `db:"admin_api_token_id" json:"admin_api_token_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	AdminUserID          string             `db:"admin_user_id" json:"admin_user_id"`
	Name                 string             `db:"name" json:"name"`
	TokenHash            []byte             `db:"token_hash" json:"token_hash"`
	TokenHint            string             `db:"token_hint" json:"token_hint"`
	Scopes               []string           `db:"scopes" json:"scopes"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt           pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason         *string            `db:"revoke_reason" json:"revoke_reason"`
}

type AdminBootstrapToken struct {
	AdminBootstrapTokenID string             `db:"admin_bootstrap_token_id" json:"admin_bootstrap_token_id"`
	Generation            int16              `db:"generation" json:"generation"`
	TokenHash             []byte             `db:"token_hash" json:"token_hash"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	ConsumedByAdminUserID *string            `db:"consumed_by_admin_user_id" json:"consumed_by_admin_user_id"`
}

type AdminMembership struct {
	AdminMembershipID    string             `db:"admin_membership_id" json:"admin_membership_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	AdminUserID          string             `db:"admin_user_id" json:"admin_user_id"`
	Role                 string             `db:"role" json:"role"`
	Status               string             `db:"status" json:"status"`
	CreatedByAdminUserID *string            `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt           pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type AdminPasswordCredential struct {
	AdminUserID        string             `db:"admin_user_id" json:"admin_user_id"`
	PasswordHash       string             `db:"password_hash" json:"password_hash"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ChangedAt          pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ResetByAdminUserID *string            `db:"reset_by_admin_user_id" json:"reset_by_admin_user_id"`
}

type AdminSession struct {
	AdminSessionID string             `db:"admin_session_id" json:"admin_session_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	AdminUserID    string             `db:"admin_user_id" json:"admin_user_id"`
	TokenHash      []byte             `db:"token_hash" json:"token_hash"`
	TokenHint      string             `db:"token_hint" json:"token_hint"`
	CsrfTokenHash  []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason   *string            `db:"revoke_reason" json:"revoke_reason"`
}

type AdminUser struct {
	AdminUserID           string             `db:"admin_user_id" json:"admin_user_id"`
	Email                 string             `db:"email" json:"email"`
	EmailNormalized       string             `db:"email_normalized" json:"email_normalized"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Status                string             `db:"status" json:"status"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt            pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	PasswordResetRequired bool               `db:"password_reset_required" json:"password_reset_required"`
}

type Application struct {
	ApplicationID  string             `db:"application_id" json:"application_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type ApplicationUser struct {
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	Status            string             `db:"status" json:"status"`
	NormalizedClaims  []byte             `db:"normalized_claims" json:"normalized_claims"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	BlockedAt         pgtype.Timestamptz `db:"blocked_at" json:"blocked_at"`
}

type AttestationEvent struct {
	AttestationEventID string  `db:"attestation_event_id" json:"attestation_event_id"`
	OrganizationID     string  `db:"organization_id" json:"organization_id"`
	ApplicationID      string  `db:"application_id" json:"application_id"`
	EnvironmentID      string  `db:"environment_id" json:"environment_id"`
	InstallationID     *string `db:"installation_id" json:"installation_id"`
	// Immutable audit correlation ID. Challenges may be removed after their retention window.
	SessionChallengeID *string            `db:"session_challenge_id" json:"session_challenge_id"`
	Provider           string             `db:"provider" json:"provider"`
	Outcome            string             `db:"outcome" json:"outcome"`
	TrustLevel         *string            `db:"trust_level" json:"trust_level"`
	EvidenceHash       []byte             `db:"evidence_hash" json:"evidence_hash"`
	NormalizedSignals  []byte             `db:"normalized_signals" json:"normalized_signals"`
	FailureCode        *string            `db:"failure_code" json:"failure_code"`
	OccurredAt         pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

type AttestationKey struct {
	AttestationKeyID string             `db:"attestation_key_id" json:"attestation_key_id"`
	OrganizationID   string             `db:"organization_id" json:"organization_id"`
	ApplicationID    string             `db:"application_id" json:"application_id"`
	EnvironmentID    string             `db:"environment_id" json:"environment_id"`
	InstallationID   string             `db:"installation_id" json:"installation_id"`
	Provider         string             `db:"provider" json:"provider"`
	ProviderKeyID    *string            `db:"provider_key_id" json:"provider_key_id"`
	PublicKey        []byte             `db:"public_key" json:"public_key"`
	Environment      string             `db:"environment" json:"environment"`
	SignCount        int64              `db:"sign_count" json:"sign_count"`
	Status           string             `db:"status" json:"status"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type AuditEvent struct {
	AuditEventID   string             `db:"audit_event_id" json:"audit_event_id"`
	OrganizationID *string            `db:"organization_id" json:"organization_id"`
	EnvironmentID  *string            `db:"environment_id" json:"environment_id"`
	ActorKind      string             `db:"actor_kind" json:"actor_kind"`
	ActorID        *string            `db:"actor_id" json:"actor_id"`
	Action         string             `db:"action" json:"action"`
	ResourceType   string             `db:"resource_type" json:"resource_type"`
	ResourceID     string             `db:"resource_id" json:"resource_id"`
	Outcome        string             `db:"outcome" json:"outcome"`
	RequestID      *string            `db:"request_id" json:"request_id"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type AuditEventChange struct {
	AuditEventID   string `db:"audit_event_id" json:"audit_event_id"`
	Ordinal        int16  `db:"ordinal" json:"ordinal"`
	FieldName      string `db:"field_name" json:"field_name"`
	Operation      string `db:"operation" json:"operation"`
	Classification string `db:"classification" json:"classification"`
}

type ConcurrencyLease struct {
	ConcurrencyLeaseID string             `db:"concurrency_lease_id" json:"concurrency_lease_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	QuotaBucketID      string             `db:"quota_bucket_id" json:"quota_bucket_id"`
	LogicalRequestID   string             `db:"logical_request_id" json:"logical_request_id"`
	AcquiredAt         pgtype.Timestamptz `db:"acquired_at" json:"acquired_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
}

type ConfigRevision struct {
	ConfigRevisionID     string             `db:"config_revision_id" json:"config_revision_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	RevisionNumber       int64              `db:"revision_number" json:"revision_number"`
	Etag                 string             `db:"etag" json:"etag"`
	Status               string             `db:"status" json:"status"`
	Document             []byte             `db:"document" json:"document"`
	CompiledDocument     []byte             `db:"compiled_document" json:"compiled_document"`
	ValidationErrors     []byte             `db:"validation_errors" json:"validation_errors"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ValidatedAt          pgtype.Timestamptz `db:"validated_at" json:"validated_at"`
	BaseConfigRevisionID *string            `db:"base_config_revision_id" json:"base_config_revision_id"`
	Description          *string            `db:"description" json:"description"`
	EditVersion          int64              `db:"edit_version" json:"edit_version"`
	ValidationReport     []byte             `db:"validation_report" json:"validation_report"`
	ActivatedAt          pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
}

type DpopReplayEntry struct {
	DpopReplayEntryID string             `db:"dpop_replay_entry_id" json:"dpop_replay_entry_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	SessionGrantID    string             `db:"session_grant_id" json:"session_grant_id"`
	ProofJtiHash      []byte             `db:"proof_jti_hash" json:"proof_jti_hash"`
	HttpMethod        string             `db:"http_method" json:"http_method"`
	HttpUriHash       []byte             `db:"http_uri_hash" json:"http_uri_hash"`
	ObservedAt        pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InstallationID    string             `db:"installation_id" json:"installation_id"`
}

type Environment struct {
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Kind           string             `db:"kind" json:"kind"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type ExternalIdentity struct {
	ExternalIdentityID string             `db:"external_identity_id" json:"external_identity_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	ApplicationUserID  string             `db:"application_user_id" json:"application_user_id"`
	ProviderKey        string             `db:"provider_key" json:"provider_key"`
	IssuerHash         []byte             `db:"issuer_hash" json:"issuer_hash"`
	SubjectHmac        []byte             `db:"subject_hmac" json:"subject_hmac"`
	SelectedClaims     []byte             `db:"selected_claims" json:"selected_claims"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastVerifiedAt     pgtype.Timestamptz `db:"last_verified_at" json:"last_verified_at"`
}

type GatewaySigningKey struct {
	GatewaySigningKeyID     string             `db:"gateway_signing_key_id" json:"gateway_signing_key_id"`
	KeyID                   string             `db:"key_id" json:"key_id"`
	Algorithm               string             `db:"algorithm" json:"algorithm"`
	PublicJwk               []byte             `db:"public_jwk" json:"public_jwk"`
	EncryptionFormatVersion int16              `db:"encryption_format_version" json:"encryption_format_version"`
	MasterKeyIdentifier     string             `db:"master_key_identifier" json:"master_key_identifier"`
	EncryptedPrivateKey     []byte             `db:"encrypted_private_key" json:"encrypted_private_key"`
	Nonce                   []byte             `db:"nonce" json:"nonce"`
	Status                  string             `db:"status" json:"status"`
	NotBefore               pgtype.Timestamptz `db:"not_before" json:"not_before"`
	NotAfter                pgtype.Timestamptz `db:"not_after" json:"not_after"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RetiredAt               pgtype.Timestamptz `db:"retired_at" json:"retired_at"`
}

type IdentityProviderState struct {
	IdentityProviderStateID string             `db:"identity_provider_state_id" json:"identity_provider_state_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	ProviderKey             string             `db:"provider_key" json:"provider_key"`
	ProviderType            string             `db:"provider_type" json:"provider_type"`
	Issuer                  string             `db:"issuer" json:"issuer"`
	State                   []byte             `db:"state" json:"state"`
	JwksRefreshedAt         pgtype.Timestamptz `db:"jwks_refreshed_at" json:"jwks_refreshed_at"`
	LastErrorCode           *string            `db:"last_error_code" json:"last_error_code"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Installation struct {
	InstallationID    string             `db:"installation_id" json:"installation_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	Platform          string             `db:"platform" json:"platform"`
	DpopJkt           string             `db:"dpop_jkt" json:"dpop_jkt"`
	DpopPublicJwk     []byte             `db:"dpop_public_jwk" json:"dpop_public_jwk"`
	KeyStorage        string             `db:"key_storage" json:"key_storage"`
	TrustLevel        string             `db:"trust_level" json:"trust_level"`
	Status            string             `db:"status" json:"status"`
	AppVersion        *string            `db:"app_version" json:"app_version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason      *string            `db:"revoke_reason" json:"revoke_reason"`
}

type Job struct {
	JobID              string             `db:"job_id" json:"job_id"`
	OrganizationID     *string            `db:"organization_id" json:"organization_id"`
	EnvironmentID      *string            `db:"environment_id" json:"environment_id"`
	JobType            string             `db:"job_type" json:"job_type"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	Payload            []byte             `db:"payload" json:"payload"`
	Status             string             `db:"status" json:"status"`
	AvailableAt        pgtype.Timestamptz `db:"available_at" json:"available_at"`
	LockedAt           pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedByInstanceID *string            `db:"locked_by_instance_id" json:"locked_by_instance_id"`
	AttemptCount       int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts        int32              `db:"max_attempts" json:"max_attempts"`
	LastErrorCode      *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorDetail    *string            `db:"last_error_detail" json:"last_error_detail"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type LogicalRequest struct {
	LogicalRequestID  string             `db:"logical_request_id" json:"logical_request_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	InstallationID    string             `db:"installation_id" json:"installation_id"`
	SessionGrantID    string             `db:"session_grant_id" json:"session_grant_id"`
	ConfigRevisionID  string             `db:"config_revision_id" json:"config_revision_id"`
	FeatureKey        string             `db:"feature_key" json:"feature_key"`
	Protocol          string             `db:"protocol" json:"protocol"`
	ClientRequestID   *string            `db:"client_request_id" json:"client_request_id"`
	Status            string             `db:"status" json:"status"`
	RequestedAt       pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	DispatchedAt      pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailureCode       *string            `db:"failure_code" json:"failure_code"`
}

type Organization struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type QuotaBucket struct {
	QuotaBucketID     string             `db:"quota_bucket_id" json:"quota_bucket_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	Metric            string             `db:"metric" json:"metric"`
	ScopeType         string             `db:"scope_type" json:"scope_type"`
	ScopeKey          string             `db:"scope_key" json:"scope_key"`
	Algorithm         string             `db:"algorithm" json:"algorithm"`
	WindowKey         string             `db:"window_key" json:"window_key"`
	HardMaximum       *int64             `db:"hard_maximum" json:"hard_maximum"`
	UsedUnits         int64              `db:"used_units" json:"used_units"`
	ReservedUnits     int64              `db:"reserved_units" json:"reserved_units"`
	AvailableUnits    *int64             `db:"available_units" json:"available_units"`
	RefillNumerator   *int64             `db:"refill_numerator" json:"refill_numerator"`
	RefillDenominator *int64             `db:"refill_denominator" json:"refill_denominator"`
	RefilledAt        pgtype.Timestamptz `db:"refilled_at" json:"refilled_at"`
	Version           int64              `db:"version" json:"version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type QuotaReservation struct {
	QuotaReservationID string             `db:"quota_reservation_id" json:"quota_reservation_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID   string             `db:"logical_request_id" json:"logical_request_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	Status             string             `db:"status" json:"status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SettledAt          pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
}

type QuotaReservationEntry struct {
	QuotaReservationEntryID string `db:"quota_reservation_entry_id" json:"quota_reservation_entry_id"`
	OrganizationID          string `db:"organization_id" json:"organization_id"`
	ApplicationID           string `db:"application_id" json:"application_id"`
	EnvironmentID           string `db:"environment_id" json:"environment_id"`
	QuotaReservationID      string `db:"quota_reservation_id" json:"quota_reservation_id"`
	QuotaBucketID           string `db:"quota_bucket_id" json:"quota_bucket_id"`
	ReservedUnits           int64  `db:"reserved_units" json:"reserved_units"`
	SettledUnits            int64  `db:"settled_units" json:"settled_units"`
	ReleasedUnits           int64  `db:"released_units" json:"released_units"`
}

type RefreshToken struct {
	RefreshTokenID          string             `db:"refresh_token_id" json:"refresh_token_id"`
	FamilyID                string             `db:"family_id" json:"family_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID       string             `db:"application_user_id" json:"application_user_id"`
	InstallationID          string             `db:"installation_id" json:"installation_id"`
	SessionGrantID          string             `db:"session_grant_id" json:"session_grant_id"`
	ParentRefreshTokenID    *string            `db:"parent_refresh_token_id" json:"parent_refresh_token_id"`
	RotatedToRefreshTokenID *string            `db:"rotated_to_refresh_token_id" json:"rotated_to_refresh_token_id"`
	TokenHash               []byte             `db:"token_hash" json:"token_hash"`
	Status                  string             `db:"status" json:"status"`
	IssuedAt                pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt                  pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type RuntimeInstance struct {
	InstanceID  string             `db:"instance_id" json:"instance_id"`
	Role        string             `db:"role" json:"role"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	HeartbeatAt pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

type SecretRecord struct {
	SecretRecordID          string             `db:"secret_record_id" json:"secret_record_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	Name                    string             `db:"name" json:"name"`
	Version                 int64              `db:"version" json:"version"`
	EncryptionFormatVersion int16              `db:"encryption_format_version" json:"encryption_format_version"`
	Algorithm               string             `db:"algorithm" json:"algorithm"`
	MasterKeyIdentifier     string             `db:"master_key_identifier" json:"master_key_identifier"`
	Ciphertext              []byte             `db:"ciphertext" json:"ciphertext"`
	Nonce                   []byte             `db:"nonce" json:"nonce"`
	CreatedByAdminUserID    string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RotatedAt               pgtype.Timestamptz `db:"rotated_at" json:"rotated_at"`
	DestroyedAt             pgtype.Timestamptz `db:"destroyed_at" json:"destroyed_at"`
}

type SessionChallenge struct {
	SessionChallengeID  string             `db:"session_challenge_id" json:"session_challenge_id"`
	OrganizationID      string             `db:"organization_id" json:"organization_id"`
	ApplicationID       string             `db:"application_id" json:"application_id"`
	EnvironmentID       string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID   string             `db:"application_user_id" json:"application_user_id"`
	IdentityProviderKey string             `db:"identity_provider_key" json:"identity_provider_key"`
	Platform            string             `db:"platform" json:"platform"`
	DpopJkt             string             `db:"dpop_jkt" json:"dpop_jkt"`
	DpopPublicJwk       []byte             `db:"dpop_public_jwk" json:"dpop_public_jwk"`
	NonceHash           []byte             `db:"nonce_hash" json:"nonce_hash"`
	BindingHash         []byte             `db:"binding_hash" json:"binding_hash"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	// Public random nonce returned with the challenge; never an identity or bearer credential.
	ChallengeNonce     *string            `db:"challenge_nonce" json:"challenge_nonce"`
	IdentityVerifiedAt pgtype.Timestamptz `db:"identity_verified_at" json:"identity_verified_at"`
	// Expiry of the already-verified external identity credential; the credential itself is never persisted.
	IdentityExpiresAt pgtype.Timestamptz `db:"identity_expires_at" json:"identity_expires_at"`
	// Exact immutable active configuration revision used to issue the challenge.
	ConfigRevisionID                  string `db:"config_revision_id" json:"config_revision_id"`
	AttestationPolicyID               string `db:"attestation_policy_id" json:"attestation_policy_id"`
	AttestationProvider               string `db:"attestation_provider" json:"attestation_provider"`
	AttestationMode                   string `db:"attestation_mode" json:"attestation_mode"`
	AttestationMinimumTrustLevel      string `db:"attestation_minimum_trust_level" json:"attestation_minimum_trust_level"`
	AttestationMaximumAgeMilliseconds int64  `db:"attestation_maximum_age_milliseconds" json:"attestation_maximum_age_milliseconds"`
	// SHA-256 digest of the validated challenge-request DPoP jti; raw jti values are never persisted.
	ChallengeDpopProofJtiHash []byte `db:"challenge_dpop_proof_jti_hash" json:"challenge_dpop_proof_jti_hash"`
	ChallengeDpopHttpMethod   string `db:"challenge_dpop_http_method" json:"challenge_dpop_http_method"`
	// SHA-256 digest of the normalized challenge-request URI; raw request URIs are never persisted.
	ChallengeDpopHttpUriHash []byte `db:"challenge_dpop_http_uri_hash" json:"challenge_dpop_http_uri_hash"`
}

type SessionChallengeConsumption struct {
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	SessionChallengeID string             `db:"session_challenge_id" json:"session_challenge_id"`
	ConsumedAt         pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type SessionGrant struct {
	SessionGrantID     string             `db:"session_grant_id" json:"session_grant_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID  string             `db:"application_user_id" json:"application_user_id"`
	InstallationID     string             `db:"installation_id" json:"installation_id"`
	AccessTokenJtiHash []byte             `db:"access_token_jti_hash" json:"access_token_jti_hash"`
	DpopJkt            string             `db:"dpop_jkt" json:"dpop_jkt"`
	PolicyRevisionID   string             `db:"policy_revision_id" json:"policy_revision_id"`
	TrustLevel         string             `db:"trust_level" json:"trust_level"`
	IdentityVerifiedAt pgtype.Timestamptz `db:"identity_verified_at" json:"identity_verified_at"`
	AttestedAt         pgtype.Timestamptz `db:"attested_at" json:"attested_at"`
	IssuedAt           pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt          pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason       *string            `db:"revoke_reason" json:"revoke_reason"`
	// Configured identity provider used for this grant; never a raw external subject or credential.
	IdentityProviderKey *string `db:"identity_provider_key" json:"identity_provider_key"`
	// Expiry of the external identity proof used for this grant; no raw identity credential is stored.
	IdentityExpiresAt    pgtype.Timestamptz `db:"identity_expires_at" json:"identity_expires_at"`
	AttestationProvider  *string            `db:"attestation_provider" json:"attestation_provider"`
	AttestationExpiresAt pgtype.Timestamptz `db:"attestation_expires_at" json:"attestation_expires_at"`
}

type UpstreamAttempt struct {
	UpstreamAttemptID string             `db:"upstream_attempt_id" json:"upstream_attempt_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID  string             `db:"logical_request_id" json:"logical_request_id"`
	AttemptNumber     int32              `db:"attempt_number" json:"attempt_number"`
	RouteKey          string             `db:"route_key" json:"route_key"`
	UpstreamKey       string             `db:"upstream_key" json:"upstream_key"`
	PhysicalModel     *string            `db:"physical_model" json:"physical_model"`
	Status            string             `db:"status" json:"status"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FirstByteAt       pgtype.Timestamptz `db:"first_byte_at" json:"first_byte_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	HttpStatus        *int32             `db:"http_status" json:"http_status"`
	FailureCode       *string            `db:"failure_code" json:"failure_code"`
	BilledCostNanoUsd *int64             `db:"billed_cost_nano_usd" json:"billed_cost_nano_usd"`
	Currency          *string            `db:"currency" json:"currency"`
	PriceRevision     *string            `db:"price_revision" json:"price_revision"`
	PricingSource     *string            `db:"pricing_source" json:"pricing_source"`
	CostConfidence    *string            `db:"cost_confidence" json:"cost_confidence"`
}

type UsageRecord struct {
	UsageRecordID     string             `db:"usage_record_id" json:"usage_record_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID  string             `db:"logical_request_id" json:"logical_request_id"`
	UpstreamAttemptID *string            `db:"upstream_attempt_id" json:"upstream_attempt_id"`
	Metric            string             `db:"metric" json:"metric"`
	Units             int64              `db:"units" json:"units"`
	CostNanoUsd       *int64             `db:"cost_nano_usd" json:"cost_nano_usd"`
	Currency          *string            `db:"currency" json:"currency"`
	PriceRevision     *string            `db:"price_revision" json:"price_revision"`
	PricingSource     *string            `db:"pricing_source" json:"pricing_source"`
	Confidence        string             `db:"confidence" json:"confidence"`
	ProvenanceKey     string             `db:"provenance_key" json:"provenance_key"`
	RecordedAt        pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type UsageRollupsDaily struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	BucketDate     pgtype.Date        `db:"bucket_date" json:"bucket_date"`
	DimensionKey   string             `db:"dimension_key" json:"dimension_key"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	Metric         string             `db:"metric" json:"metric"`
	Units          int64              `db:"units" json:"units"`
	CostNanoUsd    int64              `db:"cost_nano_usd" json:"cost_nano_usd"`
	RequestCount   int64              `db:"request_count" json:"request_count"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageRollupsHourly struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	BucketStart    pgtype.Timestamptz `db:"bucket_start" json:"bucket_start"`
	DimensionKey   string             `db:"dimension_key" json:"dimension_key"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	Metric         string             `db:"metric" json:"metric"`
	Units          int64              `db:"units" json:"units"`
	CostNanoUsd    int64              `db:"cost_nano_usd" json:"cost_nano_usd"`
	RequestCount   int64              `db:"request_count" json:"request_count"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserOverride struct {
	UserOverrideID       string             `db:"user_override_id" json:"user_override_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID    string             `db:"application_user_id" json:"application_user_id"`
	OverrideDocument     []byte             `db:"override_document" json:"override_document"`
	Reason               string             `db:"reason" json:"reason"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}
