// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveConfigRevision struct {
	OrganizationID         string             `db:"organization_id" json:"organization_id"`
	ApplicationID          string             `db:"application_id" json:"application_id"`
	EnvironmentID          string             `db:"environment_id" json:"environment_id"`
	ConfigRevisionID       string             `db:"config_revision_id" json:"config_revision_id"`
	RevisionStatus         string             `db:"revision_status" json:"revision_status"`
	ActivatedByAdminUserID string             `db:"activated_by_admin_user_id" json:"activated_by_admin_user_id"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
}

type AdminApiToken struct {
	AdminApiTokenID      string             `db:"admin_api_token_id" json:"admin_api_token_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	AdminUserID          string             `db:"admin_user_id" json:"admin_user_id"`
	Name                 string             `db:"name" json:"name"`
	TokenHash            []byte             `db:"token_hash" json:"token_hash"`
	TokenHint            string             `db:"token_hint" json:"token_hint"`
	Scopes               []string           `db:"scopes" json:"scopes"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt           pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason         *string            `db:"revoke_reason" json:"revoke_reason"`
}

type AdminBootstrapToken struct {
	AdminBootstrapTokenID string             `db:"admin_bootstrap_token_id" json:"admin_bootstrap_token_id"`
	Generation            int16              `db:"generation" json:"generation"`
	TokenHash             []byte             `db:"token_hash" json:"token_hash"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	ConsumedByAdminUserID *string            `db:"consumed_by_admin_user_id" json:"consumed_by_admin_user_id"`
}

type AdminMembership struct {
	AdminMembershipID    string             `db:"admin_membership_id" json:"admin_membership_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	AdminUserID          string             `db:"admin_user_id" json:"admin_user_id"`
	Role                 string             `db:"role" json:"role"`
	Status               string             `db:"status" json:"status"`
	CreatedByAdminUserID *string            `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt           pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type AdminPasswordCredential struct {
	AdminUserID        string             `db:"admin_user_id" json:"admin_user_id"`
	PasswordHash       string             `db:"password_hash" json:"password_hash"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ChangedAt          pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ResetByAdminUserID *string            `db:"reset_by_admin_user_id" json:"reset_by_admin_user_id"`
}

type AdminSession struct {
	AdminSessionID string             `db:"admin_session_id" json:"admin_session_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	AdminUserID    string             `db:"admin_user_id" json:"admin_user_id"`
	TokenHash      []byte             `db:"token_hash" json:"token_hash"`
	TokenHint      string             `db:"token_hint" json:"token_hint"`
	CsrfTokenHash  []byte             `db:"csrf_token_hash" json:"csrf_token_hash"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason   *string            `db:"revoke_reason" json:"revoke_reason"`
}

type AdminUser struct {
	AdminUserID           string             `db:"admin_user_id" json:"admin_user_id"`
	Email                 string             `db:"email" json:"email"`
	EmailNormalized       string             `db:"email_normalized" json:"email_normalized"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Status                string             `db:"status" json:"status"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt            pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	PasswordResetRequired bool               `db:"password_reset_required" json:"password_reset_required"`
}

type AppAttestKeyCommitReceipt struct {
	CommitToken      []byte             `db:"commit_token" json:"commit_token"`
	OrganizationID   string             `db:"organization_id" json:"organization_id"`
	ApplicationID    string             `db:"application_id" json:"application_id"`
	EnvironmentID    string             `db:"environment_id" json:"environment_id"`
	AttestationKeyID string             `db:"attestation_key_id" json:"attestation_key_id"`
	SignCount        int64              `db:"sign_count" json:"sign_count"`
	CommittedAt      pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Application struct {
	ApplicationID  string             `db:"application_id" json:"application_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type ApplicationUser struct {
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	Status            string             `db:"status" json:"status"`
	NormalizedClaims  []byte             `db:"normalized_claims" json:"normalized_claims"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	BlockedAt         pgtype.Timestamptz `db:"blocked_at" json:"blocked_at"`
}

type AttestationEvent struct {
	AttestationEventID string  `db:"attestation_event_id" json:"attestation_event_id"`
	OrganizationID     string  `db:"organization_id" json:"organization_id"`
	ApplicationID      string  `db:"application_id" json:"application_id"`
	EnvironmentID      string  `db:"environment_id" json:"environment_id"`
	InstallationID     *string `db:"installation_id" json:"installation_id"`
	// Immutable audit correlation ID. Challenges may be removed after their retention window.
	SessionChallengeID    *string            `db:"session_challenge_id" json:"session_challenge_id"`
	Provider              string             `db:"provider" json:"provider"`
	Outcome               string             `db:"outcome" json:"outcome"`
	TrustLevel            *string            `db:"trust_level" json:"trust_level"`
	EvidenceHash          []byte             `db:"evidence_hash" json:"evidence_hash"`
	NormalizedSignals     []byte             `db:"normalized_signals" json:"normalized_signals"`
	FailureCode           *string            `db:"failure_code" json:"failure_code"`
	OccurredAt            pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	InstallationFamilyID  *string            `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID     *string            `db:"client_component_id" json:"client_component_id"`
	TrustSource           *string            `db:"trust_source" json:"trust_source"`
	ParentComponentID     *string            `db:"parent_component_id" json:"parent_component_id"`
	ComponentDelegationID *string            `db:"component_delegation_id" json:"component_delegation_id"`
}

type AttestationKey struct {
	AttestationKeyID      string             `db:"attestation_key_id" json:"attestation_key_id"`
	OrganizationID        string             `db:"organization_id" json:"organization_id"`
	ApplicationID         string             `db:"application_id" json:"application_id"`
	EnvironmentID         string             `db:"environment_id" json:"environment_id"`
	InstallationID        *string            `db:"installation_id" json:"installation_id"`
	Provider              string             `db:"provider" json:"provider"`
	ProviderKeyID         *string            `db:"provider_key_id" json:"provider_key_id"`
	PublicKey             []byte             `db:"public_key" json:"public_key"`
	Environment           string             `db:"environment" json:"environment"`
	SignCount             int64              `db:"sign_count" json:"sign_count"`
	Status                string             `db:"status" json:"status"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RevokedAt             pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ApplicationUserID     string             `db:"application_user_id" json:"application_user_id"`
	BindingEnvironment    string             `db:"binding_environment" json:"binding_environment"`
	Platform              string             `db:"platform" json:"platform"`
	DpopJkt               string             `db:"dpop_jkt" json:"dpop_jkt"`
	ProviderKeyHash       []byte             `db:"provider_key_hash" json:"provider_key_hash"`
	AppIDHash             []byte             `db:"app_id_hash" json:"app_id_hash"`
	LastAssertionHash     []byte             `db:"last_assertion_hash" json:"last_assertion_hash"`
	ExtensionsPresent     *bool              `db:"extensions_present" json:"extensions_present"`
	ValidationCategory    *int64             `db:"validation_category" json:"validation_category"`
	BundleVersion         *string            `db:"bundle_version" json:"bundle_version"`
	AttestedAtUnixSeconds *int64             `db:"attested_at_unix_seconds" json:"attested_at_unix_seconds"`
	AttestedAtNanosecond  *int32             `db:"attested_at_nanosecond" json:"attested_at_nanosecond"`
	LinkedAt              pgtype.Timestamptz `db:"linked_at" json:"linked_at"`
	InstallationFamilyID  *string            `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID     *string            `db:"client_component_id" json:"client_component_id"`
	ComponentKeyID        *string            `db:"component_key_id" json:"component_key_id"`
}

type AuditEvent struct {
	AuditEventID   string             `db:"audit_event_id" json:"audit_event_id"`
	OrganizationID *string            `db:"organization_id" json:"organization_id"`
	EnvironmentID  *string            `db:"environment_id" json:"environment_id"`
	ActorKind      string             `db:"actor_kind" json:"actor_kind"`
	ActorID        *string            `db:"actor_id" json:"actor_id"`
	Action         string             `db:"action" json:"action"`
	ResourceType   string             `db:"resource_type" json:"resource_type"`
	ResourceID     string             `db:"resource_id" json:"resource_id"`
	Outcome        string             `db:"outcome" json:"outcome"`
	RequestID      *string            `db:"request_id" json:"request_id"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type AuditEventChange struct {
	AuditEventID   string `db:"audit_event_id" json:"audit_event_id"`
	Ordinal        int16  `db:"ordinal" json:"ordinal"`
	FieldName      string `db:"field_name" json:"field_name"`
	Operation      string `db:"operation" json:"operation"`
	Classification string `db:"classification" json:"classification"`
}

type ClientComponent struct {
	ClientComponentID             string             `db:"client_component_id" json:"client_component_id"`
	OrganizationID                string             `db:"organization_id" json:"organization_id"`
	ApplicationID                 string             `db:"application_id" json:"application_id"`
	EnvironmentID                 string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID             string             `db:"application_user_id" json:"application_user_id"`
	InstallationFamilyID          string             `db:"installation_family_id" json:"installation_family_id"`
	ComponentDefinitionID         string             `db:"component_definition_id" json:"component_definition_id"`
	ComponentKind                 string             `db:"component_kind" json:"component_kind"`
	Platform                      string             `db:"platform" json:"platform"`
	IsRoot                        bool               `db:"is_root" json:"is_root"`
	Status                        string             `db:"status" json:"status"`
	CurrentComponentKeyID         *string            `db:"current_component_key_id" json:"current_component_key_id"`
	TrustSource                   string             `db:"trust_source" json:"trust_source"`
	TrustAttestationProvider      *string            `db:"trust_attestation_provider" json:"trust_attestation_provider"`
	TrustParentComponentID        *string            `db:"trust_parent_component_id" json:"trust_parent_component_id"`
	TrustParentAttestationEventID *string            `db:"trust_parent_attestation_event_id" json:"trust_parent_attestation_event_id"`
	TrustDelegationID             *string            `db:"trust_delegation_id" json:"trust_delegation_id"`
	TrustVerifiedAt               pgtype.Timestamptz `db:"trust_verified_at" json:"trust_verified_at"`
	TrustExpiresAt                pgtype.Timestamptz `db:"trust_expires_at" json:"trust_expires_at"`
	TrustSignals                  []byte             `db:"trust_signals" json:"trust_signals"`
	GrantedFeatures               []byte             `db:"granted_features" json:"granted_features"`
	KeyStorageClaim               string             `db:"key_storage_claim" json:"key_storage_claim"`
	AppVersion                    *string            `db:"app_version" json:"app_version"`
	SdkVersion                    *string            `db:"sdk_version" json:"sdk_version"`
	CreatedAt                     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt                    pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt                     pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason              *string            `db:"revocation_reason" json:"revocation_reason"`
}

type ComponentAttestationChallenge struct {
	ComponentAttestationChallengeID   string             `db:"component_attestation_challenge_id" json:"component_attestation_challenge_id"`
	OrganizationID                    string             `db:"organization_id" json:"organization_id"`
	ApplicationID                     string             `db:"application_id" json:"application_id"`
	EnvironmentID                     string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID                 string             `db:"application_user_id" json:"application_user_id"`
	InstallationFamilyID              string             `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID                 string             `db:"client_component_id" json:"client_component_id"`
	ComponentKeyID                    string             `db:"component_key_id" json:"component_key_id"`
	ConfigRevisionID                  string             `db:"config_revision_id" json:"config_revision_id"`
	Platform                          string             `db:"platform" json:"platform"`
	DpopJkt                           string             `db:"dpop_jkt" json:"dpop_jkt"`
	NonceHash                         []byte             `db:"nonce_hash" json:"nonce_hash"`
	BindingHash                       []byte             `db:"binding_hash" json:"binding_hash"`
	ChallengeNonce                    string             `db:"challenge_nonce" json:"challenge_nonce"`
	AttestationPolicyID               string             `db:"attestation_policy_id" json:"attestation_policy_id"`
	AttestationProvider               string             `db:"attestation_provider" json:"attestation_provider"`
	AttestationMode                   string             `db:"attestation_mode" json:"attestation_mode"`
	AttestationMinimumTrustLevel      string             `db:"attestation_minimum_trust_level" json:"attestation_minimum_trust_level"`
	AttestationMaximumAgeMilliseconds int64              `db:"attestation_maximum_age_milliseconds" json:"attestation_maximum_age_milliseconds"`
	CreatedAt                         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt                        pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type ComponentDefinition struct {
	EnvironmentID         string             `db:"environment_id" json:"environment_id"`
	ConfigRevisionID      string             `db:"config_revision_id" json:"config_revision_id"`
	ComponentDefinitionID string             `db:"component_definition_id" json:"component_definition_id"`
	Platform              string             `db:"platform" json:"platform"`
	ComponentKind         string             `db:"component_kind" json:"component_kind"`
	FamilyRole            string             `db:"family_role" json:"family_role"`
	Definition            []byte             `db:"definition" json:"definition"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ComponentDelegation struct {
	ComponentDelegationID    string             `db:"component_delegation_id" json:"component_delegation_id"`
	OrganizationID           string             `db:"organization_id" json:"organization_id"`
	ApplicationID            string             `db:"application_id" json:"application_id"`
	EnvironmentID            string             `db:"environment_id" json:"environment_id"`
	InstallationFamilyID     string             `db:"installation_family_id" json:"installation_family_id"`
	ParentComponentID        string             `db:"parent_component_id" json:"parent_component_id"`
	ChildComponentID         string             `db:"child_component_id" json:"child_component_id"`
	ChildComponentKeyID      string             `db:"child_component_key_id" json:"child_component_key_id"`
	ParentSessionGrantID     string             `db:"parent_session_grant_id" json:"parent_session_grant_id"`
	FeatureScopes            []byte             `db:"feature_scopes" json:"feature_scopes"`
	ConfigurationRevisionID  string             `db:"configuration_revision_id" json:"configuration_revision_id"`
	ParentAttestationEventID *string            `db:"parent_attestation_event_id" json:"parent_attestation_event_id"`
	IdentityProviderKey      string             `db:"identity_provider_key" json:"identity_provider_key"`
	TrustLevel               string             `db:"trust_level" json:"trust_level"`
	IdentityVerifiedAt       pgtype.Timestamptz `db:"identity_verified_at" json:"identity_verified_at"`
	IdentityExpiresAt        pgtype.Timestamptz `db:"identity_expires_at" json:"identity_expires_at"`
	AttestedAt               pgtype.Timestamptz `db:"attested_at" json:"attested_at"`
	AttestationProvider      string             `db:"attestation_provider" json:"attestation_provider"`
	AttestationExpiresAt     pgtype.Timestamptz `db:"attestation_expires_at" json:"attestation_expires_at"`
	NonceHash                []byte             `db:"nonce_hash" json:"nonce_hash"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt               pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	RevokedAt                pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type ComponentKey struct {
	ComponentKeyID       string             `db:"component_key_id" json:"component_key_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	InstallationFamilyID string             `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID    string             `db:"client_component_id" json:"client_component_id"`
	DpopJkt              string             `db:"dpop_jkt" json:"dpop_jkt"`
	PublicJwk            []byte             `db:"public_jwk" json:"public_jwk"`
	Status               string             `db:"status" json:"status"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ReplacedAt           pgtype.Timestamptz `db:"replaced_at" json:"replaced_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type ComponentRefreshToken struct {
	ComponentRefreshTokenID          string             `db:"component_refresh_token_id" json:"component_refresh_token_id"`
	ComponentSessionFamilyID         string             `db:"component_session_family_id" json:"component_session_family_id"`
	ClientComponentID                string             `db:"client_component_id" json:"client_component_id"`
	ComponentKeyID                   string             `db:"component_key_id" json:"component_key_id"`
	SessionGrantID                   *string            `db:"session_grant_id" json:"session_grant_id"`
	GrantKind                        string             `db:"grant_kind" json:"grant_kind"`
	ParentComponentRefreshTokenID    *string            `db:"parent_component_refresh_token_id" json:"parent_component_refresh_token_id"`
	RotatedToComponentRefreshTokenID *string            `db:"rotated_to_component_refresh_token_id" json:"rotated_to_component_refresh_token_id"`
	TokenHash                        []byte             `db:"token_hash" json:"token_hash"`
	Status                           string             `db:"status" json:"status"`
	IssuedAt                         pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt                        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt                           pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt                        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type ComponentSessionFamily struct {
	ComponentSessionFamilyID string             `db:"component_session_family_id" json:"component_session_family_id"`
	OrganizationID           string             `db:"organization_id" json:"organization_id"`
	ApplicationID            string             `db:"application_id" json:"application_id"`
	EnvironmentID            string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID        string             `db:"application_user_id" json:"application_user_id"`
	InstallationFamilyID     string             `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID        string             `db:"client_component_id" json:"client_component_id"`
	ComponentKeyID           string             `db:"component_key_id" json:"component_key_id"`
	Status                   string             `db:"status" json:"status"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RevokedAt                pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason         *string            `db:"revocation_reason" json:"revocation_reason"`
}

type ConcurrencyLease struct {
	ConcurrencyLeaseID string             `db:"concurrency_lease_id" json:"concurrency_lease_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	QuotaBucketID      string             `db:"quota_bucket_id" json:"quota_bucket_id"`
	LogicalRequestID   string             `db:"logical_request_id" json:"logical_request_id"`
	AcquiredAt         pgtype.Timestamptz `db:"acquired_at" json:"acquired_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
}

type ConfigRevision struct {
	ConfigRevisionID     string             `db:"config_revision_id" json:"config_revision_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	RevisionNumber       int64              `db:"revision_number" json:"revision_number"`
	Etag                 string             `db:"etag" json:"etag"`
	Status               string             `db:"status" json:"status"`
	Document             []byte             `db:"document" json:"document"`
	CompiledDocument     []byte             `db:"compiled_document" json:"compiled_document"`
	ValidationErrors     []byte             `db:"validation_errors" json:"validation_errors"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ValidatedAt          pgtype.Timestamptz `db:"validated_at" json:"validated_at"`
	BaseConfigRevisionID *string            `db:"base_config_revision_id" json:"base_config_revision_id"`
	Description          *string            `db:"description" json:"description"`
	EditVersion          int64              `db:"edit_version" json:"edit_version"`
	ValidationReport     []byte             `db:"validation_report" json:"validation_report"`
	ActivatedAt          pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
}

type DpopReplayEntry struct {
	DpopReplayEntryID string             `db:"dpop_replay_entry_id" json:"dpop_replay_entry_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	SessionGrantID    string             `db:"session_grant_id" json:"session_grant_id"`
	ProofJtiHash      []byte             `db:"proof_jti_hash" json:"proof_jti_hash"`
	HttpMethod        string             `db:"http_method" json:"http_method"`
	HttpUriHash       []byte             `db:"http_uri_hash" json:"http_uri_hash"`
	ObservedAt        pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InstallationID    string             `db:"installation_id" json:"installation_id"`
}

type Environment struct {
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Kind           string             `db:"kind" json:"kind"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type ExternalIdentity struct {
	ExternalIdentityID string             `db:"external_identity_id" json:"external_identity_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	ApplicationUserID  string             `db:"application_user_id" json:"application_user_id"`
	ProviderKey        string             `db:"provider_key" json:"provider_key"`
	IssuerHash         []byte             `db:"issuer_hash" json:"issuer_hash"`
	SubjectHmac        []byte             `db:"subject_hmac" json:"subject_hmac"`
	SelectedClaims     []byte             `db:"selected_claims" json:"selected_claims"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastVerifiedAt     pgtype.Timestamptz `db:"last_verified_at" json:"last_verified_at"`
}

type GatewaySigningKey struct {
	GatewaySigningKeyID     string             `db:"gateway_signing_key_id" json:"gateway_signing_key_id"`
	KeyID                   string             `db:"key_id" json:"key_id"`
	Algorithm               string             `db:"algorithm" json:"algorithm"`
	PublicJwk               []byte             `db:"public_jwk" json:"public_jwk"`
	EncryptionFormatVersion int16              `db:"encryption_format_version" json:"encryption_format_version"`
	MasterKeyIdentifier     string             `db:"master_key_identifier" json:"master_key_identifier"`
	EncryptedPrivateKey     []byte             `db:"encrypted_private_key" json:"encrypted_private_key"`
	Nonce                   []byte             `db:"nonce" json:"nonce"`
	Status                  string             `db:"status" json:"status"`
	NotBefore               pgtype.Timestamptz `db:"not_before" json:"not_before"`
	NotAfter                pgtype.Timestamptz `db:"not_after" json:"not_after"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RetiredAt               pgtype.Timestamptz `db:"retired_at" json:"retired_at"`
}

type IdentityJwksCache struct {
	IssuerSha256      []byte             `db:"issuer_sha256" json:"issuer_sha256"`
	SourceSha256      []byte             `db:"source_sha256" json:"source_sha256"`
	SourceFormat      string             `db:"source_format" json:"source_format"`
	Document          []byte             `db:"document" json:"document"`
	DocumentSha256    []byte             `db:"document_sha256" json:"document_sha256"`
	Etag              *string            `db:"etag" json:"etag"`
	LastModified      pgtype.Timestamptz `db:"last_modified" json:"last_modified"`
	FetchedAt         pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	FreshUntil        pgtype.Timestamptz `db:"fresh_until" json:"fresh_until"`
	StaleUntil        pgtype.Timestamptz `db:"stale_until" json:"stale_until"`
	RefreshLeaseToken []byte             `db:"refresh_lease_token" json:"refresh_lease_token"`
	RefreshLeaseUntil pgtype.Timestamptz `db:"refresh_lease_until" json:"refresh_lease_until"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type IdentityProviderState struct {
	IdentityProviderStateID string             `db:"identity_provider_state_id" json:"identity_provider_state_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	ProviderKey             string             `db:"provider_key" json:"provider_key"`
	ProviderType            string             `db:"provider_type" json:"provider_type"`
	Issuer                  string             `db:"issuer" json:"issuer"`
	State                   []byte             `db:"state" json:"state"`
	JwksRefreshedAt         pgtype.Timestamptz `db:"jwks_refreshed_at" json:"jwks_refreshed_at"`
	LastErrorCode           *string            `db:"last_error_code" json:"last_error_code"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Installation struct {
	InstallationID    string             `db:"installation_id" json:"installation_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	Platform          string             `db:"platform" json:"platform"`
	DpopJkt           string             `db:"dpop_jkt" json:"dpop_jkt"`
	DpopPublicJwk     []byte             `db:"dpop_public_jwk" json:"dpop_public_jwk"`
	KeyStorage        string             `db:"key_storage" json:"key_storage"`
	TrustLevel        string             `db:"trust_level" json:"trust_level"`
	Status            string             `db:"status" json:"status"`
	AppVersion        *string            `db:"app_version" json:"app_version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt        pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason      *string            `db:"revoke_reason" json:"revoke_reason"`
}

type InstallationFamily struct {
	InstallationFamilyID string             `db:"installation_family_id" json:"installation_family_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID    string             `db:"application_user_id" json:"application_user_id"`
	Platform             string             `db:"platform" json:"platform"`
	Status               string             `db:"status" json:"status"`
	RootComponentID      *string            `db:"root_component_id" json:"root_component_id"`
	RootInstallationID   string             `db:"root_installation_id" json:"root_installation_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason     *string            `db:"revocation_reason" json:"revocation_reason"`
}

type Job struct {
	JobID              string             `db:"job_id" json:"job_id"`
	OrganizationID     *string            `db:"organization_id" json:"organization_id"`
	EnvironmentID      *string            `db:"environment_id" json:"environment_id"`
	JobType            string             `db:"job_type" json:"job_type"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	Payload            []byte             `db:"payload" json:"payload"`
	Status             string             `db:"status" json:"status"`
	AvailableAt        pgtype.Timestamptz `db:"available_at" json:"available_at"`
	LockedAt           pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedByInstanceID *string            `db:"locked_by_instance_id" json:"locked_by_instance_id"`
	AttemptCount       int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts        int32              `db:"max_attempts" json:"max_attempts"`
	LastErrorCode      *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorDetail    *string            `db:"last_error_detail" json:"last_error_detail"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type LogicalRequest struct {
	LogicalRequestID  string             `db:"logical_request_id" json:"logical_request_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID string             `db:"application_user_id" json:"application_user_id"`
	InstallationID    string             `db:"installation_id" json:"installation_id"`
	SessionGrantID    string             `db:"session_grant_id" json:"session_grant_id"`
	ConfigRevisionID  string             `db:"config_revision_id" json:"config_revision_id"`
	FeatureKey        string             `db:"feature_key" json:"feature_key"`
	Protocol          string             `db:"protocol" json:"protocol"`
	ClientRequestID   *string            `db:"client_request_id" json:"client_request_id"`
	Status            string             `db:"status" json:"status"`
	RequestedAt       pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	DispatchedAt      pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailureCode       *string            `db:"failure_code" json:"failure_code"`
	// Unpadded base64url SHA-256 of the canonical server-trusted request and resolved quota/routing decision. NULL is reserved for rows created before schema version 9 and cannot authorize a replay.
	TrustedDecisionFingerprint *string `db:"trusted_decision_fingerprint" json:"trusted_decision_fingerprint"`
	SelectedLimitPlanKey       string  `db:"selected_limit_plan_key" json:"selected_limit_plan_key"`
	InstallationFamilyID       *string `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID          *string `db:"client_component_id" json:"client_component_id"`
	ComponentDefinitionID      *string `db:"component_definition_id" json:"component_definition_id"`
	ComponentKind              *string `db:"component_kind" json:"component_kind"`
	TrustSource                *string `db:"trust_source" json:"trust_source"`
	Framework                  *string `db:"framework" json:"framework"`
	FrameworkVersion           *string `db:"framework_version" json:"framework_version"`
}

type Organization struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	Slug           string             `db:"slug" json:"slug"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Status         string             `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt     pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

type QuotaBucket struct {
	QuotaBucketID  string `db:"quota_bucket_id" json:"quota_bucket_id"`
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ApplicationID  string `db:"application_id" json:"application_id"`
	EnvironmentID  string `db:"environment_id" json:"environment_id"`
	Metric         string `db:"metric" json:"metric"`
	ScopeType      string `db:"scope_type" json:"scope_type"`
	// Unpadded base64url SHA-256 of a domain-separated canonical encoding of server-owned values for scope_dimensions; never a client-supplied key.
	ScopeKey          string             `db:"scope_key" json:"scope_key"`
	Algorithm         string             `db:"algorithm" json:"algorithm"`
	WindowKey         string             `db:"window_key" json:"window_key"`
	HardMaximum       *int64             `db:"hard_maximum" json:"hard_maximum"`
	UsedUnits         int64              `db:"used_units" json:"used_units"`
	ReservedUnits     int64              `db:"reserved_units" json:"reserved_units"`
	AvailableUnits    *int64             `db:"available_units" json:"available_units"`
	RefillNumerator   *int64             `db:"refill_numerator" json:"refill_numerator"`
	RefillDenominator *int64             `db:"refill_denominator" json:"refill_denominator"`
	RefilledAt        pgtype.Timestamptz `db:"refilled_at" json:"refilled_at"`
	Version           int64              `db:"version" json:"version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Canonical 1-63 character identifier of the server-selected configuration limit plan.
	LimitPlanKey string `db:"limit_plan_key" json:"limit_plan_key"`
	// Unpadded base64url SHA-256 of the canonical rule identity; mutable maximum and capacity values are excluded so policy changes do not reset usage.
	RuleKey string `db:"rule_key" json:"rule_key"`
	// Canonical configuration dimension names, including sealed installation-family/component/trust provenance and at most one normalized_claim:<name> selector; raw normalized claim values are never stored.
	ScopeDimensions []string `db:"scope_dimensions" json:"scope_dimensions"`
}

type QuotaReservation struct {
	QuotaReservationID string             `db:"quota_reservation_id" json:"quota_reservation_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID   string             `db:"logical_request_id" json:"logical_request_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	Status             string             `db:"status" json:"status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SettledAt          pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
}

type QuotaReservationEntry struct {
	QuotaReservationEntryID string `db:"quota_reservation_entry_id" json:"quota_reservation_entry_id"`
	OrganizationID          string `db:"organization_id" json:"organization_id"`
	ApplicationID           string `db:"application_id" json:"application_id"`
	EnvironmentID           string `db:"environment_id" json:"environment_id"`
	QuotaReservationID      string `db:"quota_reservation_id" json:"quota_reservation_id"`
	QuotaBucketID           string `db:"quota_bucket_id" json:"quota_bucket_id"`
	ReservedUnits           int64  `db:"reserved_units" json:"reserved_units"`
	SettledUnits            int64  `db:"settled_units" json:"settled_units"`
	ReleasedUnits           int64  `db:"released_units" json:"released_units"`
	// Immutable amount reserved when this target-scoped entry was first materialized; reserved_units may grow through later atomic retry reservations.
	InitialReservedUnits int64 `db:"initial_reserved_units" json:"initial_reserved_units"`
	// Contiguous upstream attempt that first materialized this reservation entry; schema-11 and initial schema-12 entries are attempt 1.
	OriginAttemptNumber int32 `db:"origin_attempt_number" json:"origin_attempt_number"`
}

type RefreshRotationResult struct {
	RefreshRotationResultID    string             `db:"refresh_rotation_result_id" json:"refresh_rotation_result_id"`
	OldRefreshTokenHash        []byte             `db:"old_refresh_token_hash" json:"old_refresh_token_hash"`
	ClientComponentID          string             `db:"client_component_id" json:"client_component_id"`
	ComponentKeyID             string             `db:"component_key_id" json:"component_key_id"`
	DpopJkt                    string             `db:"dpop_jkt" json:"dpop_jkt"`
	RotationResponseCiphertext []byte             `db:"rotation_response_ciphertext" json:"rotation_response_ciphertext"`
	RotationResponseNonce      []byte             `db:"rotation_response_nonce" json:"rotation_response_nonce"`
	EncryptionFormatVersion    int16              `db:"encryption_format_version" json:"encryption_format_version"`
	EncryptionAlgorithm        string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	MasterKeyIdentifier        string             `db:"master_key_identifier" json:"master_key_identifier"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type RefreshToken struct {
	RefreshTokenID          string             `db:"refresh_token_id" json:"refresh_token_id"`
	FamilyID                string             `db:"family_id" json:"family_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID       string             `db:"application_user_id" json:"application_user_id"`
	InstallationID          string             `db:"installation_id" json:"installation_id"`
	SessionGrantID          string             `db:"session_grant_id" json:"session_grant_id"`
	ParentRefreshTokenID    *string            `db:"parent_refresh_token_id" json:"parent_refresh_token_id"`
	RotatedToRefreshTokenID *string            `db:"rotated_to_refresh_token_id" json:"rotated_to_refresh_token_id"`
	TokenHash               []byte             `db:"token_hash" json:"token_hash"`
	Status                  string             `db:"status" json:"status"`
	IssuedAt                pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt                  pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type RuntimeInstance struct {
	InstanceID  string             `db:"instance_id" json:"instance_id"`
	Role        string             `db:"role" json:"role"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	HeartbeatAt pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
}

type ScheduledSelfTestRun struct {
	JobID               string             `db:"job_id" json:"job_id"`
	SelfTestScheduleID  string             `db:"self_test_schedule_id" json:"self_test_schedule_id"`
	SelfTestID          string             `db:"self_test_id" json:"self_test_id"`
	Status              string             `db:"status" json:"status"`
	BudgetDate          pgtype.Date        `db:"budget_date" json:"budget_date"`
	ReservedCostNanoUsd int64              `db:"reserved_cost_nano_usd" json:"reserved_cost_nano_usd"`
	StartedAt           pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	Result              []byte             `db:"result" json:"result"`
}

type SecretRecord struct {
	SecretRecordID          string             `db:"secret_record_id" json:"secret_record_id"`
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	Name                    string             `db:"name" json:"name"`
	Version                 int64              `db:"version" json:"version"`
	EncryptionFormatVersion int16              `db:"encryption_format_version" json:"encryption_format_version"`
	Algorithm               string             `db:"algorithm" json:"algorithm"`
	MasterKeyIdentifier     string             `db:"master_key_identifier" json:"master_key_identifier"`
	Ciphertext              []byte             `db:"ciphertext" json:"ciphertext"`
	Nonce                   []byte             `db:"nonce" json:"nonce"`
	CreatedByAdminUserID    string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RotatedAt               pgtype.Timestamptz `db:"rotated_at" json:"rotated_at"`
	DestroyedAt             pgtype.Timestamptz `db:"destroyed_at" json:"destroyed_at"`
}

type SelfTestSchedule struct {
	SelfTestScheduleID        string             `db:"self_test_schedule_id" json:"self_test_schedule_id"`
	OrganizationID            string             `db:"organization_id" json:"organization_id"`
	ApplicationID             string             `db:"application_id" json:"application_id"`
	EnvironmentID             string             `db:"environment_id" json:"environment_id"`
	ConfigRevisionID          string             `db:"config_revision_id" json:"config_revision_id"`
	Kind                      string             `db:"kind" json:"kind"`
	UpstreamKey               string             `db:"upstream_key" json:"upstream_key"`
	ModelKey                  string             `db:"model_key" json:"model_key"`
	MaxCostNanoUsd            int64              `db:"max_cost_nano_usd" json:"max_cost_nano_usd"`
	DailyCostLimitNanoUsd     int64              `db:"daily_cost_limit_nano_usd" json:"daily_cost_limit_nano_usd"`
	IntervalSeconds           int32              `db:"interval_seconds" json:"interval_seconds"`
	AuthorizedAdminUserID     string             `db:"authorized_admin_user_id" json:"authorized_admin_user_id"`
	AuthorizationMethod       string             `db:"authorization_method" json:"authorization_method"`
	AuthorizationCredentialID string             `db:"authorization_credential_id" json:"authorization_credential_id"`
	Status                    string             `db:"status" json:"status"`
	NextRunAt                 pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastEnqueuedAt            pgtype.Timestamptz `db:"last_enqueued_at" json:"last_enqueued_at"`
	DisabledAt                pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	DisabledReasonCode        *string            `db:"disabled_reason_code" json:"disabled_reason_code"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SelfTestScheduleSecretBinding struct {
	SelfTestScheduleID string `db:"self_test_schedule_id" json:"self_test_schedule_id"`
	Ordinal            int16  `db:"ordinal" json:"ordinal"`
	OrganizationID     string `db:"organization_id" json:"organization_id"`
	ApplicationID      string `db:"application_id" json:"application_id"`
	EnvironmentID      string `db:"environment_id" json:"environment_id"`
	SecretReference    string `db:"secret_reference" json:"secret_reference"`
	SecretRecordID     string `db:"secret_record_id" json:"secret_record_id"`
	SecretVersion      int64  `db:"secret_version" json:"secret_version"`
}

type SessionChallenge struct {
	SessionChallengeID  string             `db:"session_challenge_id" json:"session_challenge_id"`
	OrganizationID      string             `db:"organization_id" json:"organization_id"`
	ApplicationID       string             `db:"application_id" json:"application_id"`
	EnvironmentID       string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID   string             `db:"application_user_id" json:"application_user_id"`
	IdentityProviderKey string             `db:"identity_provider_key" json:"identity_provider_key"`
	Platform            string             `db:"platform" json:"platform"`
	DpopJkt             string             `db:"dpop_jkt" json:"dpop_jkt"`
	DpopPublicJwk       []byte             `db:"dpop_public_jwk" json:"dpop_public_jwk"`
	NonceHash           []byte             `db:"nonce_hash" json:"nonce_hash"`
	BindingHash         []byte             `db:"binding_hash" json:"binding_hash"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	// Public random nonce returned with the challenge; never an identity or bearer credential.
	ChallengeNonce     *string            `db:"challenge_nonce" json:"challenge_nonce"`
	IdentityVerifiedAt pgtype.Timestamptz `db:"identity_verified_at" json:"identity_verified_at"`
	// Expiry of the already-verified external identity credential; the credential itself is never persisted.
	IdentityExpiresAt pgtype.Timestamptz `db:"identity_expires_at" json:"identity_expires_at"`
	// Exact immutable active configuration revision used to issue the challenge.
	ConfigRevisionID                  string `db:"config_revision_id" json:"config_revision_id"`
	AttestationPolicyID               string `db:"attestation_policy_id" json:"attestation_policy_id"`
	AttestationProvider               string `db:"attestation_provider" json:"attestation_provider"`
	AttestationMode                   string `db:"attestation_mode" json:"attestation_mode"`
	AttestationMinimumTrustLevel      string `db:"attestation_minimum_trust_level" json:"attestation_minimum_trust_level"`
	AttestationMaximumAgeMilliseconds int64  `db:"attestation_maximum_age_milliseconds" json:"attestation_maximum_age_milliseconds"`
	// SHA-256 digest of the validated challenge-request DPoP jti; raw jti values are never persisted.
	ChallengeDpopProofJtiHash []byte `db:"challenge_dpop_proof_jti_hash" json:"challenge_dpop_proof_jti_hash"`
	ChallengeDpopHttpMethod   string `db:"challenge_dpop_http_method" json:"challenge_dpop_http_method"`
	// SHA-256 digest of the normalized challenge-request URI; raw request URIs are never persisted.
	ChallengeDpopHttpUriHash []byte `db:"challenge_dpop_http_uri_hash" json:"challenge_dpop_http_uri_hash"`
}

type SessionChallengeConsumption struct {
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	SessionChallengeID string             `db:"session_challenge_id" json:"session_challenge_id"`
	ConsumedAt         pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type SessionGrant struct {
	SessionGrantID     string             `db:"session_grant_id" json:"session_grant_id"`
	OrganizationID     string             `db:"organization_id" json:"organization_id"`
	ApplicationID      string             `db:"application_id" json:"application_id"`
	EnvironmentID      string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID  string             `db:"application_user_id" json:"application_user_id"`
	InstallationID     string             `db:"installation_id" json:"installation_id"`
	AccessTokenJtiHash []byte             `db:"access_token_jti_hash" json:"access_token_jti_hash"`
	DpopJkt            string             `db:"dpop_jkt" json:"dpop_jkt"`
	PolicyRevisionID   string             `db:"policy_revision_id" json:"policy_revision_id"`
	TrustLevel         string             `db:"trust_level" json:"trust_level"`
	IdentityVerifiedAt pgtype.Timestamptz `db:"identity_verified_at" json:"identity_verified_at"`
	AttestedAt         pgtype.Timestamptz `db:"attested_at" json:"attested_at"`
	IssuedAt           pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt          pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt          pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason       *string            `db:"revoke_reason" json:"revoke_reason"`
	// Configured identity provider used for this grant; never a raw external subject or credential.
	IdentityProviderKey *string `db:"identity_provider_key" json:"identity_provider_key"`
	// Expiry of the external identity proof used for this grant; no raw identity credential is stored.
	IdentityExpiresAt        pgtype.Timestamptz `db:"identity_expires_at" json:"identity_expires_at"`
	AttestationProvider      *string            `db:"attestation_provider" json:"attestation_provider"`
	AttestationExpiresAt     pgtype.Timestamptz `db:"attestation_expires_at" json:"attestation_expires_at"`
	InstallationFamilyID     *string            `db:"installation_family_id" json:"installation_family_id"`
	ClientComponentID        *string            `db:"client_component_id" json:"client_component_id"`
	ComponentDefinitionID    *string            `db:"component_definition_id" json:"component_definition_id"`
	ComponentKind            *string            `db:"component_kind" json:"component_kind"`
	ComponentIsRoot          *bool              `db:"component_is_root" json:"component_is_root"`
	TrustSource              *string            `db:"trust_source" json:"trust_source"`
	ComponentSessionFamilyID *string            `db:"component_session_family_id" json:"component_session_family_id"`
}

type UpstreamAttempt struct {
	UpstreamAttemptID             string             `db:"upstream_attempt_id" json:"upstream_attempt_id"`
	OrganizationID                string             `db:"organization_id" json:"organization_id"`
	ApplicationID                 string             `db:"application_id" json:"application_id"`
	EnvironmentID                 string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID              string             `db:"logical_request_id" json:"logical_request_id"`
	AttemptNumber                 int32              `db:"attempt_number" json:"attempt_number"`
	RouteKey                      string             `db:"route_key" json:"route_key"`
	UpstreamKey                   string             `db:"upstream_key" json:"upstream_key"`
	PhysicalModel                 *string            `db:"physical_model" json:"physical_model"`
	Status                        string             `db:"status" json:"status"`
	StartedAt                     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FirstByteAt                   pgtype.Timestamptz `db:"first_byte_at" json:"first_byte_at"`
	CompletedAt                   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	HttpStatus                    *int32             `db:"http_status" json:"http_status"`
	FailureCode                   *string            `db:"failure_code" json:"failure_code"`
	BilledCostNanoUsd             *int64             `db:"billed_cost_nano_usd" json:"billed_cost_nano_usd"`
	Currency                      *string            `db:"currency" json:"currency"`
	PriceRevision                 *string            `db:"price_revision" json:"price_revision"`
	PricingSource                 *string            `db:"pricing_source" json:"pricing_source"`
	CostConfidence                *string            `db:"cost_confidence" json:"cost_confidence"`
	ModelKey                      *string            `db:"model_key" json:"model_key"`
	AttemptDecisionBindingVersion int16              `db:"attempt_decision_binding_version" json:"attempt_decision_binding_version"`
	AttemptDecisionSha256         []byte             `db:"attempt_decision_sha256" json:"attempt_decision_sha256"`
	PerRequestOutputTokenBound    *int64             `db:"per_request_output_token_bound" json:"per_request_output_token_bound"`
	InputAccountingBindingVersion int16              `db:"input_accounting_binding_version" json:"input_accounting_binding_version"`
	InputAccountingMethod         *string            `db:"input_accounting_method" json:"input_accounting_method"`
	InputAccountingProfileID      *string            `db:"input_accounting_profile_id" json:"input_accounting_profile_id"`
	InputAccountingProfileDigest  []byte             `db:"input_accounting_profile_digest" json:"input_accounting_profile_digest"`
	RewrittenBodySha256           []byte             `db:"rewritten_body_sha256" json:"rewritten_body_sha256"`
	InputTokenBound               *int64             `db:"input_token_bound" json:"input_token_bound"`
	// Exact server-applied generated-token maximum: zero only for a protocol without generated tokens, positive for generative protocols.
	OutputTokenBound                 *int64 `db:"output_token_bound" json:"output_token_bound"`
	TotalTokenBound                  *int64 `db:"total_token_bound" json:"total_token_bound"`
	RequestMeasurementBindingVersion int16  `db:"request_measurement_binding_version" json:"request_measurement_binding_version"`
	// SHA-256 of the exact post-rewrite request body measured before dispatch; never a client-supplied digest.
	RequestMeasurementSha256 []byte `db:"request_measurement_sha256" json:"request_measurement_sha256"`
	// Exact byte length of request_measurement_sha256 body; zero is valid for a bodyless opaque request.
	MeasuredRequestBytes *int64 `db:"measured_request_bytes" json:"measured_request_bytes"`
	// Exact structured image-unit count, or NULL when the selected protocol cannot prove it.
	MeasuredImageUnits *int64 `db:"measured_image_units" json:"measured_image_units"`
	// Exact structured historical tool-call count, or NULL when the selected protocol cannot prove it.
	MeasuredToolCalls *int64 `db:"measured_tool_calls" json:"measured_tool_calls"`
}

// Per-dispatch token and cost allocations and their conservative settlement under one logical quota reservation.
type UpstreamAttemptQuotaEntry struct {
	OrganizationID          string             `db:"organization_id" json:"organization_id"`
	ApplicationID           string             `db:"application_id" json:"application_id"`
	EnvironmentID           string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID        string             `db:"logical_request_id" json:"logical_request_id"`
	UpstreamAttemptID       string             `db:"upstream_attempt_id" json:"upstream_attempt_id"`
	QuotaReservationID      string             `db:"quota_reservation_id" json:"quota_reservation_id"`
	QuotaReservationEntryID string             `db:"quota_reservation_entry_id" json:"quota_reservation_entry_id"`
	QuotaBucketID           string             `db:"quota_bucket_id" json:"quota_bucket_id"`
	Metric                  string             `db:"metric" json:"metric"`
	AllocatedUnits          int64              `db:"allocated_units" json:"allocated_units"`
	ChargedUnits            *int64             `db:"charged_units" json:"charged_units"`
	ReleasedUnits           *int64             `db:"released_units" json:"released_units"`
	SettledAt               pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
}

type UsageRecord struct {
	UsageRecordID     string             `db:"usage_record_id" json:"usage_record_id"`
	OrganizationID    string             `db:"organization_id" json:"organization_id"`
	ApplicationID     string             `db:"application_id" json:"application_id"`
	EnvironmentID     string             `db:"environment_id" json:"environment_id"`
	LogicalRequestID  string             `db:"logical_request_id" json:"logical_request_id"`
	UpstreamAttemptID *string            `db:"upstream_attempt_id" json:"upstream_attempt_id"`
	Metric            string             `db:"metric" json:"metric"`
	Units             int64              `db:"units" json:"units"`
	CostNanoUsd       *int64             `db:"cost_nano_usd" json:"cost_nano_usd"`
	Currency          *string            `db:"currency" json:"currency"`
	PriceRevision     *string            `db:"price_revision" json:"price_revision"`
	PricingSource     *string            `db:"pricing_source" json:"pricing_source"`
	Confidence        string             `db:"confidence" json:"confidence"`
	ProvenanceKey     string             `db:"provenance_key" json:"provenance_key"`
	RecordedAt        pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type UsageRollupsDaily struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	BucketDate     pgtype.Date        `db:"bucket_date" json:"bucket_date"`
	DimensionKey   string             `db:"dimension_key" json:"dimension_key"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	Metric         string             `db:"metric" json:"metric"`
	Units          int64              `db:"units" json:"units"`
	CostNanoUsd    int64              `db:"cost_nano_usd" json:"cost_nano_usd"`
	RequestCount   int64              `db:"request_count" json:"request_count"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UsageRollupsHourly struct {
	OrganizationID string             `db:"organization_id" json:"organization_id"`
	ApplicationID  string             `db:"application_id" json:"application_id"`
	EnvironmentID  string             `db:"environment_id" json:"environment_id"`
	BucketStart    pgtype.Timestamptz `db:"bucket_start" json:"bucket_start"`
	DimensionKey   string             `db:"dimension_key" json:"dimension_key"`
	Dimensions     []byte             `db:"dimensions" json:"dimensions"`
	Metric         string             `db:"metric" json:"metric"`
	Units          int64              `db:"units" json:"units"`
	CostNanoUsd    int64              `db:"cost_nano_usd" json:"cost_nano_usd"`
	RequestCount   int64              `db:"request_count" json:"request_count"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserOverride struct {
	UserOverrideID       string             `db:"user_override_id" json:"user_override_id"`
	OrganizationID       string             `db:"organization_id" json:"organization_id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	EnvironmentID        string             `db:"environment_id" json:"environment_id"`
	ApplicationUserID    string             `db:"application_user_id" json:"application_user_id"`
	OverrideDocument     []byte             `db:"override_document" json:"override_document"`
	Reason               string             `db:"reason" json:"reason"`
	CreatedByAdminUserID string             `db:"created_by_admin_user_id" json:"created_by_admin_user_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}
