// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminSessionView(ctx context.Context, adminUserID string) ([]AdminSessionViewRow, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (CreateApplicationRow, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (CreateEnvironmentRow, error)
	CreateOrganization(ctx context.Context, organizationID string, slug string, displayName string, createdAt pgtype.Timestamptz) (CreateOrganizationRow, error)
	ListApplications(ctx context.Context, organizationID string, column2 pgtype.Timestamptz, createdAt pgtype.Timestamptz, limit int32) ([]ListApplicationsRow, error)
	ListEnvironments(ctx context.Context, organizationID string, applicationID string) ([]ListEnvironmentsRow, error)
	ListOrganizationsForAdmin(ctx context.Context, adminUserID string, column2 pgtype.Timestamptz, createdAt pgtype.Timestamptz, limit int32) ([]ListOrganizationsForAdminRow, error)
}

var _ Querier = (*Queries)(nil)
