import assert from "node:assert/strict";
import test from "node:test";

import {
  generateReleaseConfig,
  parseArguments,
  releaseConfigurationMode,
  validateCustomDomain,
  validateGeneratedReleaseConfig,
  validateImmutableImageReference,
  validateReleaseConfig,
} from "./prepare-release-config.mjs";

const digest = "a".repeat(64);
const domain = "ai.example.com";
const base = `{
  "main": "src/index.ts",
  "vars": {
    "LATCHWAY_MIGRATE_ON_START": "true",
    "LATCHWAY_DB_MAX_CONNECTIONS": "5",
    "LATCHWAY_DB_COMPLETION_CONNECTIONS": "2"
  },
  "secrets": {
    "required": [
      "LATCHWAY_DATABASE_URL",
      "LATCHWAY_MASTER_KEY",
      "LATCHWAY_PUBLIC_ORIGIN",
      "LATCHWAY_ADMIN_BOOTSTRAP_TOKEN"
    ]
  },
  "containers": [
    {
      "name": "latchway",
      "image": "../../Dockerfile",
      "image_build_context": "../..",
      "max_instances": 4
    }
  ]
}\n`;

test("accepts immutable references from every supported registry", () => {
  for (const image of [
    `registry.cloudflare.com/123456/latchway@sha256:${digest}`,
    `docker.io/latchway/latchway@sha256:${digest}`,
    `123456789012.dkr.ecr.us-east-1.amazonaws.com/latchway@sha256:${digest}`,
    `us-central1-docker.pkg.dev/project/repository/latchway@sha256:${digest}`,
  ]) {
    assert.equal(validateImmutableImageReference(image), image);
  }
});

test("rejects mutable, unsupported, and malformed image references", () => {
  for (const image of [
    "docker.io/latchway/latchway:latest",
    `ghcr.io/latchway/latchway@sha256:${digest}`,
    `docker.io/Latchway/latchway@sha256:${digest}`,
    "docker.io/latchway/latchway@sha256:abc",
    `https://docker.io/latchway/latchway@sha256:${digest}`,
  ]) {
    assert.throws(() => validateImmutableImageReference(image));
  }
});

test("replaces the source build with exactly one immutable image", () => {
  const image = `registry.cloudflare.com/123456/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image, { domain });
  assert.equal(validateReleaseConfig(generated), image);
  assert.match(generated, /Generated by scripts\/prepare-release-config/);
  assert.equal(generated.includes("../../Dockerfile"), false);
  assert.equal(generated.includes("image_build_context"), false);
  assert.equal(releaseConfigurationMode(generated), "bootstrap");
  assert.match(generated, /"LATCHWAY_DB_COMPLETION_CONNECTIONS": "2"/u);
  assert.match(generated, /"pattern": "ai\.example\.com"/u);
  assert.match(generated, /"custom_domain": true/u);
});

test("generates a coherent post-bootstrap config from the same source", () => {
  const image = `registry.cloudflare.com/123456/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image, {
    domain,
    postBootstrap: true,
  });
  assert.equal(validateReleaseConfig(generated), image);
  assert.equal(releaseConfigurationMode(generated), "post-bootstrap");
  assert.match(generated, /mode: post-bootstrap/u);
  assert.match(generated, /"LATCHWAY_MIGRATE_ON_START": "false"/u);
  assert.doesNotMatch(generated, /LATCHWAY_ADMIN_BOOTSTRAP_TOKEN/u);
});

test("fails closed when the reviewed source image block drifts", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  assert.throws(
    () =>
      generateReleaseConfig(
        base.replace("../../Dockerfile", "./Dockerfile"),
        image,
        { domain },
      ),
    /drifted/,
  );
  assert.throws(
    () => generateReleaseConfig(`${base}${base}`, image, { domain }),
    /drifted/,
  );
});

test("rejects a release configuration that can rebuild source", () => {
  assert.throws(() => validateReleaseConfig(base), /mutable Dockerfile/);
});

test("accepts pnpm's explicit argument separator", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  assert.equal(
    parseArguments(["--", "--image", image, "--domain", domain]).image,
    image,
  );
  assert.equal(
    parseArguments([
      "--",
      "--image",
      image,
      "--domain",
      domain,
      "--post-bootstrap",
    ])
      .postBootstrap,
    true,
  );
});

test("validates one exact custom-domain hostname", () => {
  assert.equal(validateCustomDomain(domain), domain);
  for (const value of [
    "https://ai.example.com",
    "AI.example.com",
    "*.example.com",
    "example",
    "-ai.example.com",
    "ai.example.com/path",
  ]) {
    assert.throws(() => validateCustomDomain(value), /lowercase DNS hostname/u);
  }
});

test("requires the custom domain in generated and checked release configs", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  assert.throws(() => generateReleaseConfig(base, image), /domain/u);
  assert.throws(
    () => parseArguments(["--image", image]),
    /--domain is required/u,
  );
  const generated = generateReleaseConfig(base, image, { domain });
  assert.throws(
    () =>
      validateReleaseConfig(
        generated.replace('      "custom_domain": true\n', ""),
      ),
    /exactly one custom domain/u,
  );
  assert.throws(
    () => validateReleaseConfig(`${generated}\n{"routes": []}\n`),
    /exactly one custom domain/u,
  );
});

test("checked release config must byte-match deterministic generation", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image, { domain });
  assert.deepEqual(validateGeneratedReleaseConfig(generated, base), {
    domain,
    image,
    mode: "bootstrap",
  });
  assert.throws(
    () =>
      validateGeneratedReleaseConfig(
        generated.replace(
          '  "routes": [',
          '  /* route disabled\n  "routes": [',
        ).replace('  ],\n\n  "containers": [', '  ],\n  */\n\n  "containers": ['),
        base,
      ),
    /exactly match deterministic generation/u,
  );
  assert.throws(
    () => validateGeneratedReleaseConfig(`${generated}\n// extra\n`, base),
    /exactly match deterministic generation/u,
  );
});

test("rejects incoherent bootstrap lifecycle combinations", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image, { domain });
  assert.throws(
    () => validateReleaseConfig(
      generated.replace(
        '"LATCHWAY_MIGRATE_ON_START": "true"',
        '"LATCHWAY_MIGRATE_ON_START": "false"',
      ),
    ),
    /bootstrap lifecycle is incoherent/u,
  );
});
