import assert from "node:assert/strict";
import test from "node:test";

import {
  generateReleaseConfig,
  parseArguments,
  releaseConfigurationMode,
  validateImmutableImageReference,
  validateReleaseConfig,
} from "./prepare-release-config.mjs";

const digest = "a".repeat(64);
const base = `{
  "main": "src/index.ts",
  "vars": {
    "LATCHWAY_MIGRATE_ON_START": "true",
    "LATCHWAY_DB_MAX_CONNECTIONS": "5"
  },
  "secrets": {
    "required": [
      "LATCHWAY_DATABASE_URL",
      "LATCHWAY_MASTER_KEY",
      "LATCHWAY_PUBLIC_ORIGIN",
      "LATCHWAY_ADMIN_BOOTSTRAP_TOKEN"
    ]
  },
  "containers": [
    {
      "name": "latchway",
      "image": "../../Dockerfile",
      "image_build_context": "../..",
      "max_instances": 4
    }
  ]
}\n`;

test("accepts immutable references from every supported registry", () => {
  for (const image of [
    `registry.cloudflare.com/123456/latchway@sha256:${digest}`,
    `docker.io/latchway/latchway@sha256:${digest}`,
    `123456789012.dkr.ecr.us-east-1.amazonaws.com/latchway@sha256:${digest}`,
    `us-central1-docker.pkg.dev/project/repository/latchway@sha256:${digest}`,
  ]) {
    assert.equal(validateImmutableImageReference(image), image);
  }
});

test("rejects mutable, unsupported, and malformed image references", () => {
  for (const image of [
    "docker.io/latchway/latchway:latest",
    `ghcr.io/latchway/latchway@sha256:${digest}`,
    `docker.io/Latchway/latchway@sha256:${digest}`,
    "docker.io/latchway/latchway@sha256:abc",
    `https://docker.io/latchway/latchway@sha256:${digest}`,
  ]) {
    assert.throws(() => validateImmutableImageReference(image));
  }
});

test("replaces the source build with exactly one immutable image", () => {
  const image = `registry.cloudflare.com/123456/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image);
  assert.equal(validateReleaseConfig(generated), image);
  assert.match(generated, /Generated by scripts\/prepare-release-config/);
  assert.equal(generated.includes("../../Dockerfile"), false);
  assert.equal(generated.includes("image_build_context"), false);
  assert.equal(releaseConfigurationMode(generated), "bootstrap");
});

test("generates a coherent post-bootstrap config from the same source", () => {
  const image = `registry.cloudflare.com/123456/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image, { postBootstrap: true });
  assert.equal(validateReleaseConfig(generated), image);
  assert.equal(releaseConfigurationMode(generated), "post-bootstrap");
  assert.match(generated, /mode: post-bootstrap/u);
  assert.match(generated, /"LATCHWAY_MIGRATE_ON_START": "false"/u);
  assert.doesNotMatch(generated, /LATCHWAY_ADMIN_BOOTSTRAP_TOKEN/u);
});

test("fails closed when the reviewed source image block drifts", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  assert.throws(
    () => generateReleaseConfig(base.replace("../../Dockerfile", "./Dockerfile"), image),
    /drifted/,
  );
  assert.throws(() => generateReleaseConfig(`${base}${base}`, image), /drifted/);
});

test("rejects a release configuration that can rebuild source", () => {
  assert.throws(() => validateReleaseConfig(base), /mutable Dockerfile/);
});

test("accepts pnpm's explicit argument separator", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  assert.equal(parseArguments(["--", "--image", image]).image, image);
  assert.equal(
    parseArguments(["--", "--image", image, "--post-bootstrap"])
      .postBootstrap,
    true,
  );
});

test("rejects incoherent bootstrap lifecycle combinations", () => {
  const image = `docker.io/latchway/latchway@sha256:${digest}`;
  const generated = generateReleaseConfig(base, image);
  assert.throws(
    () => validateReleaseConfig(
      generated.replace('"LATCHWAY_MIGRATE_ON_START": "true"', '"LATCHWAY_MIGRATE_ON_START": "false"'),
    ),
    /bootstrap lifecycle is incoherent/u,
  );
});
