package problem

// Registry mirrors api/error-codes.yaml. Keep the titles/status/retryability
// stable for a contract version; guidance remains documentation-only.
var Registry = map[string]Definition{
	"request_invalid":                       {400, "Invalid request", false},
	"identity_token_missing":                {401, "Identity token required", false},
	"identity_token_invalid":                {401, "Identity token invalid", false},
	"identity_token_expired":                {401, "Identity token expired", false},
	"identity_reauthentication_required":    {401, "Identity reauthentication required", false},
	"attestation_required":                  {401, "Attestation required", false},
	"attestation_unsupported":               {400, "Attestation unsupported", false},
	"attestation_invalid":                   {401, "Attestation invalid", false},
	"attestation_stale":                     {401, "Attestation stale", false},
	"attestation_step_up_required":          {401, "Stronger attestation required", false},
	"dpop_missing":                          {401, "DPoP proof required", false},
	"dpop_invalid":                          {401, "DPoP proof invalid", false},
	"dpop_replayed":                         {401, "DPoP proof replayed", false},
	"dpop_nonce_required":                   {401, "DPoP nonce required", true},
	"session_expired":                       {401, "Session expired", true},
	"session_revoked":                       {401, "Session revoked", false},
	"refresh_token_reused":                  {401, "Refresh token reuse detected", false},
	"installation_revoked":                  {403, "Installation revoked", false},
	"installation_family_revoked":           {403, "Installation family revoked", false},
	"installation_family_not_found":         {404, "Installation family not found", false},
	"component_definition_not_found":        {404, "Component definition not found", false},
	"component_not_configured":              {422, "Component not configured", false},
	"component_not_provisioned":             {403, "Component not provisioned", false},
	"component_revoked":                     {403, "Component revoked", false},
	"component_key_invalid":                 {401, "Component key invalid", false},
	"component_key_replaced":                {401, "Component key replaced", false},
	"component_delegation_expired":          {401, "Component delegation expired", false},
	"component_feature_not_granted":         {403, "Component feature not granted", false},
	"component_parent_trust_expired":        {401, "Parent component trust expired", false},
	"component_direct_attestation_required": {401, "Direct component attestation required", false},
	"containing_app_setup_required":         {409, "Containing app setup required", false},
	"framework_integration_unsupported":     {400, "Framework integration unsupported", false},
	"framework_version_unsupported":         {400, "Framework version unsupported", false},
	"transport_destination_not_allowed":     {403, "Transport destination not allowed", false},
	"transport_request_not_replayable":      {409, "Transport request not replayable", false},
	"feature_not_found":                     {404, "Feature not found", false},
	"feature_not_allowed":                   {403, "Feature not allowed", false},
	"model_not_allowed":                     {403, "Model not allowed", false},
	"quota_exceeded":                        {429, "Quota exceeded", true},
	"concurrency_exceeded":                  {429, "Concurrency limit exceeded", true},
	"output_limit_exceeded":                 {400, "Output limit exceeded", false},
	"pricing_unavailable":                   {503, "Pricing unavailable", true},
	"route_not_found":                       {503, "No route available", true},
	"upstream_unavailable":                  {503, "Upstream unavailable", true},
	"upstream_timeout":                      {504, "Upstream timeout", false},
	"upstream_protocol_error":               {502, "Upstream protocol error", false},
	"configuration_invalid":                 {422, "Configuration invalid", false},
	"server_not_ready":                      {503, "Server not ready", true},
	"protocol_version_unsupported":          {426, "Protocol version unsupported", false},
	"authentication_required":               {401, "Administrator authentication required", false},
	"permission_denied":                     {403, "Permission denied", false},
	"resource_not_found":                    {404, "Resource not found", false},
	"conflict":                              {409, "Resource conflict", false},
	"etag_required":                         {428, "ETag required", false},
	"etag_mismatch":                         {412, "ETag mismatch", false},
	"bootstrap_disabled":                    {409, "Bootstrap disabled", false},
	"rate_limited":                          {429, "Rate limited", true},
	"operation_indeterminate":               {503, "Operation outcome indeterminate", true},
	"internal_error":                        {500, "Internal server error", false},
}
