// Package console exposes the production admin-console bundle to the Go server.
package console

import (
	"embed"
	"io/fs"
)

// distribution contains the reproducible assets generated by pnpm build.
// The all: prefix includes nested asset directories and dot-prefixed files.
//
//go:embed all:dist
var distribution embed.FS

// Assets returns a filesystem rooted at dist. The HTTP server must reserve API
// paths and use index.html as a fallback only for client-side console routes.
func Assets() (fs.FS, error) {
	return fs.Sub(distribution, "dist")
}
